//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaatveSaatApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingOrder
    {
        public int PendingOrderProductId { get; set; }
        public int PendingOrderProductPiece { get; set; }
        public System.DateTime PendingOrderCreateDate { get; set; }
        public System.DateTime PendingOrderUpdateDate { get; set; }
        public int OrderId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
