//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaatveSaatApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaatvesaatDBEntities : DbContext
    {
        public SaatvesaatDBEntities()
            : base("name=SaatvesaatDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BrandCategory> BrandCategory { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CompletedOrder> CompletedOrder { get; set; }
        public virtual DbSet<PendingOrder> PendingOrder { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
